Support TPM image registration setting
SUSE-Enceladus/ec2imgutils pull request #84
Opened 2022-05-20 20:52 UTC by rjschwei

+ AWS has announced the NitroTPM feature, i.e. a VTPM attached to certain
  instances. If an image is TPM capable or not is set during image
  registration, similar to ena, sriov, and boot-mode setting. Add the
  --tpm-support option to the CLI and tpm_support argument to the API.

2022-05-20 21:01 UTC, smarlowucf requested changes

2022-05-20 21:01 UTC, smarlowucf commented on ec2uploadimg
> +    choices=['', '2.0'],
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.register_image

2022-05-20 23:07 UTC, rjschwei commented on ec2uploadimg
> +    choices=['', '2.0'],
The `v` gets added in the implementation

https://github.com/SUSE-Enceladus/ec2imgutils/pull/84/files#diff-4a37e5f13564c40d30d98fb8a73669b812d37dc91e3911a6ef85da95d02dde1aR887

2022-05-23 11:24 UTC, apozsuse approved these changes
LGTM
Once you merge this branch into master I'll include these changes into the refactor and the tests.

2022-05-24 13:43 UTC, merged