Refactor for the ec2listimg script
SUSE-Enceladus/ec2imgutils pull request #86
Opened 2022-05-25 10:44 UTC by apozsuse

# Changes
- Functionality in the script has been encapsulated into functions
- Added tests to verify argument/config management and script functionality (mocking some boto3 response)

2022-05-25 16:29 UTC, smarlowucf approved these changes

2022-05-25 19:55 UTC, rjschwei requested changes

2022-05-25 19:55 UTC, rjschwei commented on ec2listimg
> +    line args and config files.
s/and config files/or configuration/

Stating "config files" is misleading as the function expects a config object.

2022-05-25 19:55 UTC, rjschwei commented on ec2listimg
> +    line args and config files
ditto

2022-05-25 19:55 UTC, rjschwei commented on ec2listimg
> +def get_lister(args, access_key, secret_key, logger, regions):
s/get_lister/get_image_lister/

2022-05-27 12:54 UTC, rjschwei approved these changes

2022-05-27 12:54 UTC, merged