Refactor for ec2removeimage script
SUSE-Enceladus/ec2imgutils pull request #87
Opened 2022-05-26 10:22 UTC by apozsuse

- Functionality in the script has been encapsulated into functions
- Added tests to verify argument/config management and script functionality (mocking some boto3 response)

2022-05-26 13:36 UTC, smarlowucf approved these changes

2022-05-27 12:32 UTC, rjschwei requested changes

2022-05-27 12:32 UTC, rjschwei commented on ec2removeimg
> +    """Commang argument parsing function."""
s/Commang/Command/

2022-05-27 12:32 UTC, rjschwei commented on ec2removeimg
> +    """This function is used to assure the additional requirements over
s/assure/ensure/

2022-05-27 12:32 UTC, rjschwei commented on ec2removeimg
> +    """Function to the the configutation parsed from the configuration file
"the the" maybe "get the" ?

2022-05-27 13:12 UTC, apozsuse commented on ec2removeimg
> +    """Commang argument parsing function."""
done

2022-05-27 13:21 UTC, rjschwei approved these changes

2022-05-27 13:21 UTC, merged