Return with non-0 exit code on uploadimg failure
SUSE-Enceladus/ec2imgutils pull request #94
Opened 2022-07-19 11:31 UTC by grisu48

This commit adds an error handling logic to the upload_image procedure
so that the program terminates with a non-0 return code on upload
errors.

2022-07-19 12:19 UTC, rjschwei requested changes
While you are here, please move the two `global` statements outside of the try block, i.e.

```
global setup
global uploader
try:
    setup = ....
```

2022-07-19 12:19 UTC, rjschwei commented on ec2uploadimg
> +            setup.clean_up()
If an exception occurs during clean up the code will not reach `sys.exit(1)`, i.e. we are missing part of the intended fix.

2022-07-19 15:50 UTC, apozsuse commented
Hi! [This one](https://github.com/SUSE-Enceladus/ec2imgutils/blob/master/tests/test_ec2uploadimg.py#L1325
) might be a good example for a testcase where you can see how the class can be mocked.

There you can see the "'ec2uploadimg.ec2upimg.EC2ImageUploader" class mocked and you can define the return values for the different class functions that we'd need for the test (as done in that specific example with the .return_value method), or you can raise exceptions in the mocked class methods (with the .side_effect method, [example here](https://github.com/SUSE-Enceladus/ec2imgutils/blob/db4ac66b470383157cf90c8860aef1dd61e83cdb/tests/test_ec2uploadimg.py#L770).

Please, give it a thought and do not hesitate to contact me if you have any question about the testing.

2022-07-20 09:36 UTC, grisu48 commented
I added a test case and so far execution of `py.test tests/test_ec2uploadimg.py` looks fine.

```
============================================ test session starts =============================================
platform linux -- Python 3.10.5, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/phoenix/QAC/ec2imgutils
plugins: anyio-3.5.0, testinfra-6.3.0
collected 63 items                                                                                           

tests/test_ec2uploadimg.py ...............................................................             [100%]

============================================== warnings summary ==============================================
<frozen importlib._bootstrap>:283
  <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead

../../../../usr/lib/python3.10/site-packages/invoke/loader.py:3
  /usr/lib/python3.10/site-packages/invoke/loader.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================= 63 passed, 2 warnings in 0.33s =======================================
```

I also checked wheather the test case is actually executed, by deliberately changing it to fail and `py.test` yells at me just as it should be :slightly_smiling_face: 

```
========================================== short test summary info ===========================================
FAILED tests/test_ec2uploadimg.py::test_failed_upload - assert 1 == 0
================================== 1 failed, 62 passed, 2 warnings in 0.58s ==================================
```

***

Btw. `make test` to run, but can be easily fixed within the Makefile

```
test:
	py.test tests/test_*.py
```

This triggers 3 test failures however, that's why I'm relying on specifically calling `py.test tests/test_ec2uploadimg.py`

2022-07-20 11:46 UTC, rjschwei approved these changes

2022-07-20 11:53 UTC, apozsuse commented
LGTM :+1
Thanks!
The failing tests happen because there's some changes of ' for " in some outputs depending on the python version (In python 3.8 they pass but they seem to fail in 3.6) and the tests are asserting exact matches.  I'll fix them after this merge.

2022-07-20 11:54 UTC, apozsuse approved these changes

2022-07-20 12:37 UTC, merged